name: Create Release
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" #

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions
      COMPRESS_FILES: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up GO
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.5
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions

