name: create release
on:
  push:
    tags:
      - "v*" #

jobs:
  build:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "{{ github.ref }}"
          release_name: Release '{{ github.ref }}'
          body: ${{github.event.head_commit.message}}
          draft: false
          prerelease: false
      - name: Build binaries
        uses: sosedoff/actions/golang-build@master
      - name: Upload multi-git linux_amd64
        id: upload_multi_git_linux_amd64
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: .release/multi-git_linux_amd64.zip
          asset_name: multi-git_linux_amd64.zip
          asset_content_type: application/zip
