name: Create Release
on:
  release:
    types: [created]

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build binaries
        uses: wangyoucao577/go-release-action@v1.22
        with:
          goos: linux
          goarch: amd64
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
