name: Create Release
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" #

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions
      COMPRESS_FILES: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
      - name: Build binaries
        uses: sosedoff/actions/golang-build@master
      - name: Upload binaries
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: .release/multi-git_darwin_386.zip
          asset_name: multi-git_darwin_386.zip
          asset_content_type: application/zip
