name: create release
on:
  push:
    tags:
      - "0*"

jobs:
  build:
    name: Create release
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create release
        id: create-release
        uses: actions/create-release@v2
        with:
          tag_name: "{{ github.ref }}"
          release_name: Release '{{ github.ref }}'
          body: ${{github.event.head_commit.message}}
          draft: false
          prerelease: false
      - name: Build binaries
        uses: sosedoff/actions/golang-build@master
